name: vz-task

networks:
    laravel:

services:
    # Nginx Service
    nginx:
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ../src:/srv/www
        build: nginx
        networks:
            - laravel
    # PHP Service
    php-fpm:
        container_name: php-fpm
        build: php
        volumes_from:
            - nginx
        networks:
            - laravel
    # Database Service
    database:
        container_name: mysql
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: vz-task
            MYSQL_USER: vz-task-user
            MYSQL_PASSWORD: vz-task-pass
            MYSQL_ROOT_PASSWORD: admin
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel